// Production reads and status polling with synthetic deferred clients.
// No Vault, model, native fault command, or third-party page is involved.
import { spawn } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [exe, fixture, out] = process.argv.slice(2);
if (!out) throw new Error("usage: read-smoke.mjs <exe> <fixture.js> <out-dir>");
mkdirSync(out, { recursive: true });
const report = { provenance: "production Explorer, Sessions, Overlay and status hook with synthetic deferred clients", checks: [] };
const check = (name, ok) => { report.checks.push({ name, ok: Boolean(ok) }); console.log(`${ok ? "PASS" : "FAIL"} ${name}`); };
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const port = 9397;
let ws;
const app = spawn(exe, [], {
  windowsHide: true, stdio: "ignore",
  env: { ...process.env, WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS: `--remote-debugging-port=${port} --remote-debugging-address=127.0.0.1` },
});
const appError = new Promise((_, reject) => app.once("error", reject));
let evaluate;
try {
  let target;
  for (let i = 0; i < 100 && !target; i++) {
    target = await fetch(`http://127.0.0.1:${port}/json`).then((r) => r.json())
      .then((pages) => pages.find((p) => p.type === "page" && p.url.startsWith("http://tauri.localhost/") && !p.url.includes("overlay")))
      .catch(() => null);
    if (!target) await Promise.race([sleep(150), appError]);
  }
  if (!target) throw new Error("No owned app page");
  ws = new WebSocket(target.webSocketDebuggerUrl);
  const ready = new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
  let id = 0;
  const pending = new Map();
  ws.onmessage = ({ data }) => { const message = JSON.parse(data); pending.get(message.id)?.(message); pending.delete(message.id); };
  await ready;
  evaluate = async (expression) => {
    const requestId = ++id;
    const response = new Promise((resolve, reject) => {
      const timeout = setTimeout(() => { pending.delete(requestId); reject(new Error("Debugger request timed out")); }, 15000);
      pending.set(requestId, (message) => { clearTimeout(timeout); resolve(message); });
    });
    ws.send(JSON.stringify({ id: requestId, method: "Runtime.evaluate", params: { expression, awaitPromise: true, returnByValue: true } }));
    const message = await response;
    if (message.error || message.result?.exceptionDetails) throw new Error(JSON.stringify(message.error ?? message.result.exceptionDetails));
    return message.result?.result?.value;
  };
  const wait = async (expression) => {
    for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await sleep(30); }
    throw new Error(`Fixture wait failed: ${expression}`);
  };
  await wait("document.readyState === 'complete' && !!document.querySelector('#root > *')");
  await evaluate(readFileSync(fixture, "utf8"));
  await evaluate(`window.__unmountReads = MV6ReadTest.mount();
    window.__readQuery = (text) => {
      const input = document.querySelector('#read-fixture #mq');
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, text);
      input.dispatchEvent(new Event('input', {bubbles:true}));
    };
    window.__readText = () => document.querySelector('#read-fixture').innerText;`);
  await wait("MV6ReadTest.requests().length === 1");
  await evaluate("MV6ReadTest.respond(0, '')");
  const submit = async (query) => {
    const count = await evaluate("MV6ReadTest.requests().length");
    await evaluate(`__readQuery(${JSON.stringify(query)})`);
    await sleep(30);
    await evaluate("document.querySelector('#read-fixture form').requestSubmit()");
    await wait(`MV6ReadTest.requests().length === ${count + 1}`);
    return count;
  };
  const textIncludes = (text) => `__readText().includes(${JSON.stringify(text)})`;

  const old = await submit("older search");
  const latest = await submit("latest search");
  await evaluate(`MV6ReadTest.respond(${latest}, 'latest result', 'latest-page')`);
  await wait(textIncludes("latest result"));
  await evaluate(`MV6ReadTest.respond(${old}, 'obsolete result', 'obsolete-page')`);
  await sleep(100);
  check("latest_result_survives_old_success", await evaluate(`${textIncludes("latest result")} && !${textIncludes("obsolete result")}`));

  const failing = await submit("older failure");
  const successful = await submit("latest success");
  await evaluate(`MV6ReadTest.respond(${successful}, 'current successful result', 'stable-page')`);
  await wait(textIncludes("current successful result"));
  await evaluate(`MV6ReadTest.fail(${failing})`);
  await sleep(100);
  check("obsolete_failure_not_shown", await evaluate("!document.querySelector('#read-fixture [role=alert]')"));

  const olderBusy = await submit("older pending");
  const currentBusy = await submit("current pending");
  await evaluate(`MV6ReadTest.respond(${olderBusy}, 'obsolete busy result', 'obsolete-page')`);
  await sleep(100);
  check("latest_read_remains_busy", await evaluate("[...document.querySelectorAll('#read-fixture button')].find((b) => b.textContent === '加载更多')?.disabled === true"));
  await evaluate(`MV6ReadTest.respond(${currentBusy}, 'current paged result', 'current-page')`);
  await wait(textIncludes("current paged result"));

  const pageIndex = await evaluate("MV6ReadTest.requests().length");
  await evaluate("__readQuery('unsubmitted draft')");
  await sleep(30);
  await evaluate("[...document.querySelectorAll('#read-fixture button')].find((b) => b.textContent === '加载更多').click()");
  await wait(`MV6ReadTest.requests().length === ${pageIndex + 1}`);
  const pagination = await evaluate(`MV6ReadTest.requests()[${pageIndex}]`);
  check("pagination_uses_submitted_query", pagination.command === "memory_search" && pagination.args.query === "current pending" && pagination.args.cursor === "current-page");
  await evaluate(`MV6ReadTest.respond(${pageIndex}, 'next page')`);
  await wait(textIncludes("next page"));
  check("pagination_appends_current_page", await evaluate(`${textIncludes("current paged result")} && ${textIncludes("next page")}`));

  const filterIndex = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#read-fixture input[type=checkbox]').click()");
  await wait(`MV6ReadTest.requests().length === ${filterIndex + 1}`);
  const filter = await evaluate(`MV6ReadTest.requests()[${filterIndex}]`);
  check("history_filter_retains_submitted_query", filter.command === "memory_search" && filter.args.query === "current pending" && filter.args.includeHistorical === true && filter.args.cursor === null);
  await evaluate(`MV6ReadTest.respond(${filterIndex}, 'filtered result')`);
  await wait(textIncludes("filtered result"));
  const empty = await submit("missing result");
  await evaluate(`MV6ReadTest.respond(${empty}, '')`);
  await wait("__readText().includes('没有可见的已批准记忆。')");
  check("empty_result_clears_previous_rows", await evaluate(`!${textIncludes("filtered result")}`));

  const retryIndex = await submit("retry submitted query");
  await evaluate(`MV6ReadTest.fail(${retryIndex})`);
  await wait("!!document.querySelector('#read-fixture [role=alert] button')");
  await evaluate("__readQuery('retry unsubmitted draft')");
  await sleep(30);
  await evaluate("document.querySelector('#read-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${retryIndex + 2}`);
  const retried = await evaluate(`MV6ReadTest.requests()[${retryIndex + 1}]`);
  check("latest_retry_uses_original_query", retried.command === "memory_search" && retried.args.query === "retry submitted query" && retried.args.cursor === null);
  await evaluate(`MV6ReadTest.respond(${retryIndex + 1}, 'retry recovered result')`);
  await wait(textIncludes("retry recovered result"));
  check("latest_retry_recovers", await evaluate("!document.querySelector('#read-fixture [role=alert]') && document.querySelector('#read-fixture [aria-busy]').getAttribute('aria-busy') === 'false'"));
  await evaluate("window.__unmountReads()");

  // Sessions use deferred synthetic responses too. No real session write
  // occurs here; the separate real-app run verifies actual IPC/Core writes.
  await evaluate(`window.__unmountSessions = MV6ReadTest.mountSessions();
    window.__sessionText = () => document.querySelector('#session-fixture').innerText;
    window.__sessionSet = (selector, value) => {
      const input = document.querySelector('#session-fixture ' + selector);
      const prototype = input.tagName === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
      Object.getOwnPropertyDescriptor(prototype, 'value').set.call(input, value);
      input.dispatchEvent(new Event('input', {bubbles:true}));
    };`);
  await wait("MV6ReadTest.requests().length === 1");
  await evaluate(`MV6ReadTest.respondValue(0, {items:[
    {sessionId:'synthetic-alpha',updatedAt:'synthetic',branches:[{branchId:'brnAlpha001',lastEventSeq:1}]},
    {sessionId:'synthetic-beta',updatedAt:'synthetic',branches:[{branchId:'brnBeta0001',lastEventSeq:1}]}
  ]})`);
  await wait("document.querySelectorAll('#session-fixture .list button').length === 2");
  const selectSession = async (name) => {
    const count = await evaluate("MV6ReadTest.requests().length");
    await evaluate(`[...document.querySelectorAll('#session-fixture .list button')].find((b) => b.textContent.includes(${JSON.stringify(name)})).click()`);
    await wait(`MV6ReadTest.requests().length === ${count + 1}`);
    return count;
  };
  const selectedIs = (name) => `[...document.querySelectorAll('#session-fixture .list button')].find((b) => b.getAttribute('aria-current') === 'true')?.textContent.includes(${JSON.stringify(name)})`;
  const sessionContains = (text) => `__sessionText().includes(${JSON.stringify(text)})`;
  const delayedAlpha = await selectSession("Alpha001");
  const selectedBeta = await selectSession("Beta0001");
  await evaluate(`MV6ReadTest.respondSession(${selectedBeta}, 'beta transcript')`);
  await wait(sessionContains("beta transcript"));
  await evaluate(`MV6ReadTest.respondSession(${delayedAlpha}, 'obsolete alpha transcript')`);
  await sleep(100);
  check("session_latest_detail_matches_selected_branch", await evaluate(`${selectedIs("Beta0001")} && ${sessionContains("beta transcript")} && !${sessionContains("obsolete alpha transcript")}`));

  const loadingAlpha = await selectSession("Alpha001");
  check("session_selection_changes_atomically_with_detail", await evaluate(selectedIs("Beta0001")));
  await evaluate(`MV6ReadTest.respondSession(${loadingAlpha}, 'alpha transcript')`);
  await wait(sessionContains("alpha transcript"));
  await evaluate("__sessionSet('#ask', 'Draft Alpha'); __sessionSet('#cp', 'Summary Alpha')");
  await sleep(30);
  const draftBeta = await selectSession("Beta0001");
  await evaluate(`MV6ReadTest.respondSession(${draftBeta}, 'beta transcript')`);
  await wait(sessionContains("beta transcript"));
  check("session_drafts_do_not_cross_branches", await evaluate("document.querySelector('#session-fixture #ask').value === '' && document.querySelector('#session-fixture #cp').value === ''"));
  await evaluate("__sessionSet('#ask', 'Draft Beta'); __sessionSet('#cp', 'Summary Beta')");
  await sleep(30);
  const restoreAlpha = await selectSession("Alpha001");
  await evaluate(`MV6ReadTest.respondSession(${restoreAlpha}, 'alpha transcript')`);
  await wait(sessionContains("alpha transcript"));
  check("session_question_draft_restored", await evaluate("document.querySelector('#session-fixture #ask').value === 'Draft Alpha'"));
  check("session_checkpoint_draft_restored", await evaluate("document.querySelector('#session-fixture #cp').value === 'Summary Alpha'"));

  const answerBeta = await selectSession("Beta0001");
  await evaluate(`MV6ReadTest.respondSession(${answerBeta}, 'beta transcript')`);
  await wait(sessionContains("beta transcript"));
  await evaluate("__sessionSet('#ask', 'Send Beta')");
  await sleep(30);
  const askIndex = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#session-fixture #ask').closest('form').requestSubmit()");
  await wait(`MV6ReadTest.requests().length === ${askIndex + 1}`);
  const askRequest = await evaluate(`MV6ReadTest.requests()[${askIndex}]`);
  check("session_write_keeps_selected_branch_and_key", askRequest.command === "session_ask" && askRequest.args.branchId === "brnBeta0001" && askRequest.args.text === "Send Beta" && typeof askRequest.key === "string");
  await evaluate(`MV6ReadTest.respondValue(${askIndex}, {status:'synthetic_completed',statements:['answer for beta'],sources:[],capsuleId:'synthetic-capsule'})`);
  await wait(`MV6ReadTest.requests().length === ${askIndex + 2}`);
  await evaluate(`MV6ReadTest.respondSession(${askIndex + 1}, 'beta after answer')`);
  await wait(sessionContains("beta after answer"));
  const afterAnswerAlpha = await selectSession("Alpha001");
  await evaluate(`MV6ReadTest.respondSession(${afterAnswerAlpha}, 'alpha transcript')`);
  await wait(sessionContains("alpha transcript"));
  check("session_answer_does_not_cross_branches", await evaluate(`!${sessionContains("answer for beta")}`));

  const oldFailure = await selectSession("Alpha001");
  const newSuccess = await selectSession("Beta0001");
  await evaluate(`MV6ReadTest.respondSession(${newSuccess}, 'beta newest transcript')`);
  await wait(sessionContains("beta newest transcript"));
  await evaluate(`MV6ReadTest.fail(${oldFailure})`);
  await sleep(100);
  check("session_obsolete_failure_not_shown", await evaluate("!document.querySelector('#session-fixture [role=alert]')"));

  await evaluate("__sessionSet('#ask', 'Persist Beta')");
  await sleep(30);
  const writingIndex = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#session-fixture #ask').closest('form').requestSubmit()");
  await wait(`MV6ReadTest.requests().length === ${writingIndex + 1}`);
  await evaluate("document.querySelector('#session-fixture .list button').click()");
  await sleep(100);
  const duringWriteCount = await evaluate("MV6ReadTest.requests().length");
  check("session_cannot_switch_during_write", duringWriteCount === writingIndex + 1 && await evaluate(selectedIs("Beta0001")));
  if (duringWriteCount > writingIndex + 1) await evaluate(`MV6ReadTest.respondSession(${writingIndex + 1}, 'alpha during write')`);
  await evaluate(`MV6ReadTest.respondValue(${writingIndex}, {status:'synthetic_completed',statements:['persisted beta answer'],sources:[],capsuleId:'synthetic-capsule'})`);
  await wait(`MV6ReadTest.requests().length === ${duringWriteCount + 1}`);
  await evaluate(`MV6ReadTest.respondSession(${duringWriteCount}, 'beta persisted transcript')`);
  await wait(sessionContains("beta persisted transcript"));
  check("session_acknowledged_write_refreshes_same_branch", await evaluate(selectedIs("Beta0001")));

  await evaluate("__sessionSet('#ask', 'Retry original Beta')");
  await sleep(30);
  const failedAsk = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#session-fixture #ask').closest('form').requestSubmit()");
  await wait(`MV6ReadTest.requests().length === ${failedAsk + 1}`);
  await evaluate(`MV6ReadTest.fail(${failedAsk})`);
  await wait("!!document.querySelector('#session-fixture [role=alert] button')");
  await evaluate("__sessionSet('#ask', 'New unsent Beta')");
  await sleep(30);
  await evaluate("document.querySelector('#session-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${failedAsk + 2}`);
  const askAttempts = await evaluate(`MV6ReadTest.requests().slice(${failedAsk}, ${failedAsk + 2})`);
  check("session_retry_keeps_original_payload_and_key", askAttempts[0].key === askAttempts[1].key && askAttempts[1].args.text === "Retry original Beta" && askAttempts[1].args.branchId === "brnBeta0001");
  check("session_retry_blocks_branch_switch", await evaluate("[...document.querySelectorAll('#session-fixture .list button')].every((b) => b.disabled)"));
  await evaluate(`MV6ReadTest.respondValue(${failedAsk + 1}, {status:'synthetic_completed',statements:['retried original beta'],sources:[],capsuleId:'synthetic-capsule'})`);
  await wait(`MV6ReadTest.requests().length === ${failedAsk + 3}`);
  await evaluate(`MV6ReadTest.respondSession(${failedAsk + 2}, 'beta after retry')`);
  await wait(sessionContains("beta after retry"));
  check("session_retry_preserves_new_unsent_question", await evaluate("document.querySelector('#session-fixture #ask').value === 'New unsent Beta'"));

  await evaluate("__sessionSet('#cp', 'Original checkpoint Beta')");
  await sleep(30);
  const failedCheckpoint = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#session-fixture #cp').closest('form').requestSubmit()");
  await wait(`MV6ReadTest.requests().length === ${failedCheckpoint + 1}`);
  await evaluate(`MV6ReadTest.fail(${failedCheckpoint})`);
  await wait("!!document.querySelector('#session-fixture [role=alert] button')");
  await evaluate("__sessionSet('#cp', 'New unsent checkpoint Beta')");
  await sleep(30);
  await evaluate("document.querySelector('#session-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${failedCheckpoint + 2}`);
  const checkpointAttempts = await evaluate(`MV6ReadTest.requests().slice(${failedCheckpoint}, ${failedCheckpoint + 2})`);
  check("session_checkpoint_retry_keeps_payload_and_key", checkpointAttempts[0].key === checkpointAttempts[1].key && checkpointAttempts[1].args.summary === "Original checkpoint Beta" && checkpointAttempts[1].args.branchId === "brnBeta0001");
  await evaluate(`MV6ReadTest.respondValue(${failedCheckpoint + 1}, {})`);
  await wait(`MV6ReadTest.requests().length === ${failedCheckpoint + 3}`);
  await evaluate(`MV6ReadTest.respondSession(${failedCheckpoint + 2}, 'beta after checkpoint')`);
  await wait(sessionContains("beta after checkpoint"));
  check("session_retry_preserves_new_unsent_checkpoint", await evaluate("document.querySelector('#session-fixture #cp').value === 'New unsent checkpoint Beta'"));
  await evaluate("window.__unmountSessions()");

  await evaluate(`window.__unmountOverlay = MV6ReadTest.mountOverlay();
    window.__overlayText = () => document.querySelector('#overlay-fixture').innerText;
    window.__overlayQuery = (value) => {
      const input = document.querySelector('#overlay-fixture #q');
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, value);
      input.dispatchEvent(new Event('input', {bubbles:true}));
    };`);
  await wait("!!document.querySelector('#overlay-fixture #q')");
  const submitOverlay = async (query) => {
    const count = await evaluate("MV6ReadTest.requests().length");
    await evaluate(`__overlayQuery(${JSON.stringify(query)})`);
    await sleep(30);
    await evaluate("document.querySelector('#overlay-fixture form').requestSubmit()");
    await wait(`MV6ReadTest.requests().length === ${count + 1}`);
    return count;
  };
  const overlayContains = (text) => `__overlayText().includes(${JSON.stringify(text)})`;
  const oldOverlay = await submitOverlay("old overlay query");
  const latestOverlay = await submitOverlay("latest overlay query");
  await evaluate(`MV6ReadTest.respond(${latestOverlay}, 'current overlay result')`);
  await wait(overlayContains("current overlay result"));
  await evaluate(`MV6ReadTest.respond(${oldOverlay}, 'old overlay result')`);
  await sleep(100);
  check("overlay_latest_success_wins", await evaluate(`${overlayContains("current overlay result")} && !${overlayContains("old overlay result")}`));
  const oldOverlayFailure = await submitOverlay("old overlay failure");
  const nextOverlay = await submitOverlay("new overlay success");
  await evaluate(`MV6ReadTest.respond(${nextOverlay}, 'new overlay result')`);
  await wait(overlayContains("new overlay result"));
  await evaluate(`MV6ReadTest.fail(${oldOverlayFailure})`);
  await sleep(100);
  check("overlay_obsolete_error_not_shown", await evaluate("!document.querySelector('#overlay-fixture [role=alert]')"));
  check("overlay_obsolete_error_does_not_clear_results", await evaluate(overlayContains("new overlay result")));
  const erasedOverlay = await submitOverlay("pending erased query");
  await evaluate("__overlayQuery('')");
  await sleep(30);
  await evaluate(`MV6ReadTest.respond(${erasedOverlay}, 'erased overlay response')`);
  await sleep(100);
  check("overlay_erasing_query_invalidates_pending_result", await evaluate("document.querySelector('#overlay-fixture .results').children.length === 0"));
  const beforeEmptyOverlay = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#overlay-fixture form').requestSubmit()");
  await sleep(50);
  check("overlay_empty_query_no_request_or_results", await evaluate(`MV6ReadTest.requests().length === ${beforeEmptyOverlay} && document.querySelector('#overlay-fixture .results').children.length === 0`));
  const oldOverlayBusy = await submitOverlay("old overlay busy");
  const latestOverlayBusy = await submitOverlay("latest overlay busy");
  await evaluate(`MV6ReadTest.respond(${oldOverlayBusy}, 'old overlay busy result')`);
  await sleep(50);
  check("overlay_latest_read_remains_busy", await evaluate("document.querySelector('#overlay-fixture main').getAttribute('aria-busy') === 'true'"));
  await evaluate(`MV6ReadTest.respond(${latestOverlayBusy}, 'ready overlay result')`);
  await wait(overlayContains("ready overlay result"));
  check("overlay_latest_completion_clears_busy", await evaluate("document.querySelector('#overlay-fixture main').getAttribute('aria-busy') === 'false'"));
  await evaluate("window.dispatchEvent(new Event('focus'))");
  await sleep(30);
  check("overlay_reopen_clears_previous_query_and_results", await evaluate("document.querySelector('#overlay-fixture #q').value === '' && document.querySelector('#overlay-fixture .results').children.length === 0"));
  const blurredOverlay = await submitOverlay("blurred overlay query");
  await evaluate("window.dispatchEvent(new Event('blur'))");
  await sleep(30);
  await evaluate(`MV6ReadTest.respond(${blurredOverlay}, 'blurred overlay response')`);
  await sleep(50);
  check("overlay_blur_invalidates_pending_read", await evaluate("document.querySelector('#overlay-fixture #q').value === '' && document.querySelector('#overlay-fixture .results').children.length === 0"));
  const retryOverlay = await submitOverlay("retry overlay query");
  await evaluate(`MV6ReadTest.fail(${retryOverlay})`);
  await wait("!!document.querySelector('#overlay-fixture [role=alert]')");
  const hasOverlayRetry = await evaluate("!!document.querySelector('#overlay-fixture [role=alert] button')");
  check("overlay_current_error_has_retry", hasOverlayRetry);
  if (hasOverlayRetry) {
    await evaluate("__overlayQuery('unsubmitted overlay draft')");
    await sleep(30);
    await evaluate("document.querySelector('#overlay-fixture [role=alert] button').click()");
    await wait(`MV6ReadTest.requests().length === ${retryOverlay + 2}`);
    const retriedOverlay = await evaluate(`MV6ReadTest.requests()[${retryOverlay + 1}]`);
    check("overlay_retry_keeps_submitted_query", retriedOverlay.args.query === "retry overlay query");
    await evaluate(`MV6ReadTest.respond(${retryOverlay + 1}, 'overlay retry recovered')`);
    await wait(overlayContains("overlay retry recovered"));
    check("overlay_retry_recovers", await evaluate("!document.querySelector('#overlay-fixture [role=alert]') && document.querySelector('#overlay-fixture main').getAttribute('aria-busy') === 'false'"));
  } else {
    check("overlay_retry_keeps_submitted_query", false);
    check("overlay_retry_recovers", false);
  }
  await evaluate("window.__unmountOverlay()");
  await evaluate("window.__unmountStatus = MV6ReadTest.mountStatus()");
  await wait("MV6ReadTest.requests().length === 1");
  await sleep(3200);
  const initialStatusReads = await evaluate("MV6ReadTest.requests().length");
  check("status_automatic_reads_are_serial", initialStatusReads === 1);
  await evaluate("document.querySelector('#status-fixture [data-refresh]').click()");
  await wait(`MV6ReadTest.requests().length === ${initialStatusReads + 1}`);
  await evaluate(`MV6ReadTest.respondValue(${initialStatusReads}, {vault:{state:'locked'}})`);
  await wait("document.querySelector('#status-fixture [data-status]').textContent.includes('locked')");
  await evaluate("MV6ReadTest.respondValue(0, {vault:{state:'open'}})");
  await sleep(100);
  check("status_old_open_cannot_overwrite_lock", await evaluate("document.querySelector('#status-fixture [data-status]').textContent.includes('locked') && !document.querySelector('#status-fixture [data-open]')"));
  // Settle any obsolete baseline interval reads before the next cases.
  for (let i = 1; i < initialStatusReads; i++) await evaluate(`MV6ReadTest.fail(${i})`);
  const oldStatusRead = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#status-fixture [data-refresh]').click()");
  await wait(`MV6ReadTest.requests().length === ${oldStatusRead + 1}`);
  await evaluate("document.querySelector('#status-fixture [data-refresh]').click()");
  await wait(`MV6ReadTest.requests().length === ${oldStatusRead + 2}`);
  await evaluate(`MV6ReadTest.respondValue(${oldStatusRead + 1}, {vault:{state:'open'}})`);
  await evaluate(`MV6ReadTest.fail(${oldStatusRead})`);
  await sleep(100);
  check("status_obsolete_error_is_ignored", await evaluate("!document.querySelector('#status-fixture [role=alert]') && document.querySelector('#status-fixture [data-status]').textContent.includes('open')"));
  const failedStatusRead = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#status-fixture [data-refresh]').click()");
  await wait(`MV6ReadTest.requests().length === ${failedStatusRead + 1}`);
  await evaluate(`MV6ReadTest.fail(${failedStatusRead})`);
  await sleep(100);
  check("status_current_failure_is_visible", await evaluate("!!document.querySelector('#status-fixture [role=alert]')"));
  check("status_failed_refresh_closes_content_gate", await evaluate("document.querySelector('#status-fixture [data-status]').textContent.includes('unknown') && !document.querySelector('#status-fixture [data-open]')"));
  const statusRetry = await evaluate("!!document.querySelector('#status-fixture [role=alert] button')");
  check("status_current_failure_can_retry", statusRetry);
  if (statusRetry) {
    await evaluate("document.querySelector('#status-fixture [role=alert] button').click()");
    await wait(`MV6ReadTest.requests().length === ${failedStatusRead + 2}`);
    check("status_retry_requests_status_only", await evaluate(`MV6ReadTest.requests()[${failedStatusRead + 1}].command === 'workspace_status'`));
    await evaluate(`MV6ReadTest.respondValue(${failedStatusRead + 1}, {vault:{state:'open'}})`);
    await wait("!!document.querySelector('#status-fixture [data-open]')");
    check("status_retry_clears_error", await evaluate("!document.querySelector('#status-fixture [role=alert]')"));
  } else {
    check("status_retry_requests_status_only", false);
    check("status_retry_clears_error", false);
  }
  await evaluate("window.__unmountStatus()");
  const statusReadsBeforeUnmount = await evaluate("MV6ReadTest.requests().length");
  await sleep(3200);
  check("status_unmount_stops_automatic_reads", await evaluate(`MV6ReadTest.requests().length === ${statusReadsBeforeUnmount}`));
  await evaluate("window.__unmountContext = MV6ReadTest.mountContext()");
  await wait("MV6ReadTest.requests().length === 1");
  await evaluate("MV6ReadTest.respondContext(0)");
  await wait("document.querySelectorAll('#context-fixture button').length === 3");
  const contextText = (text) => `document.querySelector('#context-fixture').innerText.includes(${JSON.stringify(text)})`;
  const dispatchRead = async (which) => {
    const count = await evaluate("MV6ReadTest.requests().length");
    await evaluate(`[...document.querySelectorAll('#context-fixture button')].filter(b=>b.textContent === '查看实际请求')[${which}].click()`);
    await wait(`MV6ReadTest.requests().length === ${count + 1}`);
    return count;
  };
  const dispatchA = await dispatchRead(0);
  const dispatchB = await dispatchRead(1);
  await evaluate(`MV6ReadTest.respondDispatch(${dispatchB}, 'latest dispatch B')`);
  await wait(contextText("latest dispatch B"));
  await evaluate(`MV6ReadTest.respondDispatch(${dispatchA}, 'obsolete dispatch A')`);
  await sleep(100);
  check("context_latest_dispatch_wins", await evaluate(`${contextText("latest dispatch B")} && !${contextText("obsolete dispatch A")}`));
  const oldDispatchError = await dispatchRead(0);
  const currentDispatch = await dispatchRead(1);
  await evaluate(`MV6ReadTest.respondDispatch(${currentDispatch}, 'current dispatch B')`);
  await wait(contextText("current dispatch B"));
  await evaluate(`MV6ReadTest.fail(${oldDispatchError})`);
  await sleep(100);
  check("context_obsolete_dispatch_error_ignored", await evaluate("!document.querySelector('#context-fixture [role=alert]')"));
  const failedDispatch = await dispatchRead(0);
  await evaluate(`MV6ReadTest.fail(${failedDispatch})`);
  await wait("!!document.querySelector('#context-fixture [role=alert]')");
  check("context_failed_dispatch_does_not_show_previous_request", await evaluate("!document.querySelector('#context-fixture pre.source')"));
  await evaluate("document.querySelector('#context-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${failedDispatch + 2}`);
  check("context_dispatch_retry_keeps_identity", await evaluate(`MV6ReadTest.requests()[${failedDispatch + 1}].args.dispatchId === 'synthetic-dispatch-a'`));
  await evaluate(`MV6ReadTest.respondDispatch(${failedDispatch + 1}, 'retried dispatch A')`);
  await wait(contextText("retried dispatch A"));
  const lateDispatch = await dispatchRead(1);
  await evaluate(`Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(document.querySelector('#context-fixture #cq'),'synthetic preview');document.querySelector('#context-fixture #cq').dispatchEvent(new Event('input',{bubbles:true}))`);
  await sleep(30);
  const previewWrite = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#context-fixture form').requestSubmit()");
  await wait(`MV6ReadTest.requests().length === ${previewWrite + 1}`);
  await evaluate(`MV6ReadTest.respondValue(${previewWrite}, {capsuleId:'synthetic-preview'})`);
  await wait(`MV6ReadTest.requests().length === ${previewWrite + 2}`);
  check("context_new_inspection_clears_previous_view", await evaluate(`!${contextText("已发送（见下方实际请求）")}`));
  await evaluate(`MV6ReadTest.respondContext(${previewWrite + 1}, true)`);
  await wait(contextText("仅预览：没有发送给任何目的地"));
  await evaluate(`MV6ReadTest.respondDispatch(${lateDispatch}, 'late original dispatch')`);
  await sleep(100);
  check("context_dispatch_cannot_cross_capsule", await evaluate(`!${contextText("late original dispatch")}`));
  await evaluate(`Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(document.querySelector('#context-fixture #cq'),'synthetic failed inspection');document.querySelector('#context-fixture #cq').dispatchEvent(new Event('input',{bubbles:true}))`);
  await sleep(30);
  const failedPreview = await evaluate("MV6ReadTest.requests().length");
  await evaluate("document.querySelector('#context-fixture form').requestSubmit()");
  await wait(`MV6ReadTest.requests().length === ${failedPreview + 1}`);
  await evaluate(`MV6ReadTest.respondValue(${failedPreview}, {capsuleId:'synthetic-failed-preview'})`);
  await wait(`MV6ReadTest.requests().length === ${failedPreview + 2}`);
  await evaluate(`MV6ReadTest.fail(${failedPreview + 1})`);
  await wait("!!document.querySelector('#context-fixture [role=alert] button')");
  check("context_failed_inspection_clears_previous_view", await evaluate(`!${contextText("仅预览：没有发送给任何目的地")}`));
  await evaluate("document.querySelector('#context-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${failedPreview + 3}`);
  check("context_inspection_retry_keeps_capsule", await evaluate(`MV6ReadTest.requests()[${failedPreview + 2}].command === 'context_inspect' && MV6ReadTest.requests()[${failedPreview + 2}].args.capsuleId === 'synthetic-failed-preview'`));
  await evaluate(`MV6ReadTest.respondContext(${failedPreview + 2}, true)`);
  await wait(contextText("仅预览：没有发送给任何目的地"));
  check("context_retry_clears_error", await evaluate("!document.querySelector('#context-fixture [role=alert]')"));
  await evaluate("window.__unmountContext()");
  await evaluate("window.__unmountSource = MV6ReadTest.mountSource()");
  await wait("!!document.querySelector('#source-fixture button')");
  const sourceText = (text) => `document.querySelector('#source-fixture').innerText.includes(${JSON.stringify(text)})`;
  const sourceRead = async (next = false) => {
    const count = await evaluate("MV6ReadTest.requests().length");
    await evaluate(`[...document.querySelectorAll('#source-fixture button')].find(b=>b.textContent === ${JSON.stringify(next ? "下一段" : "查看来源")}).click()`);
    await wait(`MV6ReadTest.requests().length === ${count + 1}`);
    return count;
  };
  const oldSource = await sourceRead();
  const latestSource = await sourceRead();
  await evaluate(`MV6ReadTest.respondExcerpt(${latestSource}, 'latest source excerpt')`);
  await wait(sourceText("latest source excerpt"));
  await evaluate(`MV6ReadTest.respondExcerpt(${oldSource}, 'obsolete source excerpt')`);
  await sleep(100);
  check("source_latest_excerpt_wins", await evaluate(`${sourceText("latest source excerpt")} && !${sourceText("obsolete source excerpt")}`));
  const oldSourceError = await sourceRead();
  const currentSource = await sourceRead();
  await evaluate(`MV6ReadTest.respondExcerpt(${currentSource}, 'current source excerpt')`);
  await wait(sourceText("current source excerpt"));
  await evaluate(`MV6ReadTest.fail(${oldSourceError})`);
  await sleep(100);
  check("source_obsolete_error_ignored", await evaluate("!document.querySelector('#source-fixture [role=alert]')"));
  const sourceNext = await sourceRead(true);
  const nextSourceRequest = await evaluate(`MV6ReadTest.requests()[${sourceNext}]`);
  check("source_next_range_bound_to_current_excerpt", nextSourceRequest.args.sourceId === "synthetic-source-a" && nextSourceRequest.args.sourceRevision === 1 && nextSourceRequest.args.startByte === 8);
  await evaluate(`MV6ReadTest.fail(${sourceNext})`);
  await wait("!!document.querySelector('#source-fixture [role=alert] button')");
  check("source_failed_read_clears_previous_excerpt", await evaluate("!document.querySelector('#source-fixture pre.source')"));
  await evaluate("document.querySelector('#source-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${sourceNext + 2}`);
  const retriedSource = await evaluate(`MV6ReadTest.requests()[${sourceNext + 1}]`);
  check("source_retry_keeps_range_and_revision", retriedSource.args.sourceId === "synthetic-source-a" && retriedSource.args.sourceRevision === 1 && retriedSource.args.startByte === 8);
  await evaluate(`MV6ReadTest.respondExcerpt(${sourceNext + 1}, 'retried source excerpt', 8, 16)`);
  await wait(sourceText("retried source excerpt"));
  check("source_retry_clears_error", await evaluate("!document.querySelector('#source-fixture [role=alert]')"));
  const changedSource = await sourceRead();
  await evaluate("MV6ReadTest.changeSource('synthetic-source-b', 2)");
  await sleep(50);
  check("source_identity_change_clears_previous_excerpt", await evaluate("!document.querySelector('#source-fixture pre.source')"));
  await evaluate(`MV6ReadTest.respondExcerpt(${changedSource}, 'late old source revision')`);
  await sleep(100);
  check("source_response_cannot_cross_identity", await evaluate(`!${sourceText("late old source revision")}`));
  const newSourceRead = await sourceRead();
  const newSourceRequest = await evaluate(`MV6ReadTest.requests()[${newSourceRead}]`);
  check("source_new_read_uses_current_identity", newSourceRequest.args.sourceId === "synthetic-source-b" && newSourceRequest.args.sourceRevision === 2);
  await evaluate(`MV6ReadTest.respondExcerpt(${newSourceRead}, 'new source revision')`);
  await wait(sourceText("new source revision"));
  await evaluate("MV6ReadTest.changeSource('synthetic-source-b', 2, false)");
  await sleep(50);
  check("source_withdrawn_evidence_hides_excerpt_and_read_control", await evaluate("!document.querySelector('#source-fixture pre.source') && !document.querySelector('#source-fixture button')"));
  await evaluate("window.__unmountSource()");
  await evaluate(`window.__unmountReview = MV6ReadTest.mountReview();
    window.__reviewSet = (text, claim) => {
      const area = document.querySelector('#review-fixture #rt');
      const input = document.querySelector('#review-fixture input');
      Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(area,text);
      area.dispatchEvent(new Event('input',{bubbles:true}));
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,claim);
      input.dispatchEvent(new Event('input',{bubbles:true}));
    };`);
  await wait("MV6ReadTest.requests().length === 1");
  await evaluate("MV6ReadTest.respondValue(0, {items:[],total:0})");
  await sleep(50);
  const submitReview = async (text, claim) => {
    const count = await evaluate("MV6ReadTest.requests().length");
    await evaluate(`__reviewSet(${JSON.stringify(text)},${JSON.stringify(claim)})`);
    await sleep(30);
    await evaluate("document.querySelector('#review-fixture form').requestSubmit()");
    await wait(`MV6ReadTest.requests().length === ${count + 1}`);
    return count;
  };
  const remembered = await submitReview("Original synthetic assertion", "synthetic.original");
  await evaluate(`MV6ReadTest.fail(${remembered})`);
  await wait("!!document.querySelector('#review-fixture [role=alert] button')");
  await evaluate("__reviewSet('New unsent assertion','synthetic.new')");
  await sleep(30);
  await evaluate("document.querySelector('#review-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${remembered + 2}`);
  const reviewAttempts = await evaluate(`MV6ReadTest.requests().slice(${remembered},${remembered + 2})`);
  check("review_retry_keeps_original_payload_and_key", reviewAttempts[0].key === reviewAttempts[1].key && reviewAttempts[1].args.text === "Original synthetic assertion" && reviewAttempts[1].args.claimKey === "synthetic.original");
  await evaluate(`MV6ReadTest.respondValue(${remembered + 1}, {})`);
  await wait(`MV6ReadTest.requests().length === ${remembered + 3}`);
  check("review_retry_preserves_new_unsent_text", await evaluate("document.querySelector('#review-fixture #rt').value === 'New unsent assertion'"));
  check("review_retry_preserves_new_unsent_claim", await evaluate("document.querySelector('#review-fixture input').value === 'synthetic.new'"));
  await evaluate("__reviewSet('Draft during refresh','synthetic.refresh')");
  await sleep(50);
  check("review_write_waits_for_candidate_refresh", await evaluate("document.querySelector('#review-fixture button[type=submit]').disabled"));
  await evaluate(`MV6ReadTest.respondValue(${remembered + 2}, {items:[],total:0})`);
  await sleep(50);
  const partialReview = await submitReview("Matching acknowledged text", "synthetic.old_claim");
  await evaluate("__reviewSet('Matching acknowledged text','synthetic.new_claim')");
  await sleep(30);
  await evaluate(`MV6ReadTest.respondValue(${partialReview}, {})`);
  await wait(`MV6ReadTest.requests().length === ${partialReview + 2}`);
  check("review_ack_clears_only_matching_fields", await evaluate("document.querySelector('#review-fixture #rt').value === '' && document.querySelector('#review-fixture input').value === 'synthetic.new_claim'"));
  await evaluate(`MV6ReadTest.respondValue(${partialReview + 1}, {items:[],total:0})`);
  await sleep(50);
  const normalReview = await submitReview("Final acknowledged text", "synthetic.final_claim");
  await evaluate(`MV6ReadTest.respondValue(${normalReview}, {})`);
  await wait(`MV6ReadTest.requests().length === ${normalReview + 2}`);
  check("review_ack_clears_matching_draft", await evaluate("document.querySelector('#review-fixture #rt').value === '' && document.querySelector('#review-fixture input').value === ''"));
  await evaluate(`MV6ReadTest.fail(${normalReview + 1})`);
  await wait("!!document.querySelector('#review-fixture [role=alert] button')");
  await evaluate("document.querySelector('#review-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${normalReview + 3}`);
  check("review_refresh_retry_does_not_repeat_write", await evaluate(`MV6ReadTest.requests()[${normalReview + 2}].command === 'candidate_list'`));
  await evaluate(`MV6ReadTest.respondValue(${normalReview + 2}, {items:[],total:0})`);
  await sleep(30);
  await evaluate("window.__unmountReview()");
  await evaluate(`window.__unmountCorrection = MV6ReadTest.mountCorrection();
    window.__correctionSet = text => {
      const area = document.querySelector('#correction-fixture #fix');
      Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(area,text);
      area.dispatchEvent(new Event('input',{bubbles:true}));
    };`);
  await wait("MV6ReadTest.requests().length === 1");
  await evaluate("MV6ReadTest.respondMemory(0)");
  await wait("!!document.querySelector('#correction-fixture #fix')");
  const submitCorrection = async (text) => {
    const count = await evaluate("MV6ReadTest.requests().length");
    await evaluate(`__correctionSet(${JSON.stringify(text)})`);
    await sleep(30);
    await evaluate("[...document.querySelectorAll('#correction-fixture button')].find(b=>b.textContent === '提交纠正候选').click()");
    await wait(`MV6ReadTest.requests().length === ${count + 1}`);
    return count;
  };
  const failedCorrection = await submitCorrection("Original synthetic correction");
  await evaluate(`MV6ReadTest.fail(${failedCorrection})`);
  await wait("!!document.querySelector('#correction-fixture [role=alert] button')");
  await evaluate("__correctionSet('New unsent correction')");
  await sleep(30);
  await evaluate("document.querySelector('#correction-fixture [role=alert] button').click()");
  await wait(`MV6ReadTest.requests().length === ${failedCorrection + 2}`);
  const correctionAttempts = await evaluate(`MV6ReadTest.requests().slice(${failedCorrection},${failedCorrection + 2})`);
  check("correction_retry_keeps_original_payload_revision_key", correctionAttempts[0].key === correctionAttempts[1].key && correctionAttempts[1].args.text === "Original synthetic correction" && correctionAttempts[1].args.memoryId === "synthetic-approved-memory" && correctionAttempts[1].args.revision === 7);
  await evaluate(`MV6ReadTest.respondValue(${failedCorrection + 1}, {})`);
  await sleep(50);
  check("correction_retry_preserves_new_unsent_draft", await evaluate("document.querySelector('#correction-fixture #fix').value === 'New unsent correction'"));
  const inFlightCorrection = await submitCorrection("Pending acknowledged correction");
  await evaluate("__correctionSet('New draft during correction')");
  await sleep(30);
  await evaluate(`MV6ReadTest.respondValue(${inFlightCorrection}, {})`);
  await sleep(50);
  check("correction_ack_preserves_newer_inflight_draft", await evaluate("document.querySelector('#correction-fixture #fix').value === 'New draft during correction'"));
  const matchingCorrection = await submitCorrection("Matching acknowledged correction");
  await evaluate(`MV6ReadTest.respondValue(${matchingCorrection}, {})`);
  await sleep(50);
  check("correction_ack_clears_matching_draft", await evaluate("document.querySelector('#correction-fixture #fix').value === ''"));
  check("correction_ack_keeps_approved_display_unchanged", await evaluate("document.querySelector('#correction-fixture .content').textContent === 'Original approved content'"));
  await evaluate("window.__unmountCorrection()");
} finally {
  ws?.close();
  app.kill();
  writeFileSync(join(out, "report.json"), JSON.stringify(report, null, 2));
}
if (report.checks.length !== 76 || report.checks.some((item) => !item.ok)) process.exitCode = 1;
